# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93797242424c14116f94e359192a89025f70e664cf4bc36f4ba46843b2883079e14b412dc5771fd64d1ff1c40ae770599b0dc0e26373decd82d6108e77ec31ef

test:
  secret_key_base: 03b7191ace987f78a9cc80b99bd0ec76a14534c6d23e3fed6ff7605adb485d6b040d4ae214f6763143524c128a9593327a3d1bf1283e1912156e1e9791c12f36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
