

Corporate.create!([
  {name: "Daelim Industrial", country: nil, sector: "Industrials", address: "Jongro 1-Gil, Seoul", activity: "The company is a general contractor. Backlog is fairly balanced: civil 18%, plant 10%, building 27%, overseas 28% (oil& gas and power plants), petchems 17% in 2011. 50% ownership of YNCC a naphtha cracker with hanwha - generally thought to focus upon profitability. The company has also shifted into power generation (Pocheon 33% stake)", latitude: 37.5746718, longitude: 126.9789714, urlevernote: "https://www.evernote.com/Home.action#st=p&x=daelim%2526industrial&n=796543c9-375a-4f9b-b17f-2afbe1d081bc", urlcompanywebsite: "http://eng.daelim.co.kr", Bloombergid: "000210 KS", corpimage_file_name: "daelim.jpg", corpimage_content_type: "image/jpeg", corpimage_file_size: 81774, corpimage_updated_at: "2014-10-11 11:19:32", user_id: 2, urlgooglenews: "https://www.google.co.uk/#q=daelim+industrial&tbm=nws", country: "KR"}
])
Infocat.create!([
  {title: "CV/Resume", brief_description: "An in depth review of skills and experience", itemorder: 1, routing: "resumeitems", user_id: nil},
  {title: "Downloads", brief_description: "Documents available for download", itemorder: 2, routing: "downloads", user_id: 2},
  {title: "Stock Database", brief_description: "A central hub of links to allow work flow in stock research", itemorder: 3, routing: "corporates", user_id: 2}
])
Openinfo.create!([
  {title: "Information Management", Openinformation: "If not the heart, information management is close to the heart of stock selection.  Information has flooded the industry over the past 20 years as delivery and collection collapsed in price.  It is only recently however, that the technology to control this fold and successfully irrigate ideas has appeared.", user_id: 2, Moreinformation: "", itemorder: 3},
  {title: "Information available on sign in (invitation required)", Openinformation: "Sign in gives access to my resume, detailed process information and track record data. To ask for a login please email admin@mpwa.me and I will contact you to discuss your requirements. If you have been issued with a login, please click login above. The information below is some examples of in depth content. Thanks Mark.", user_id: 2, Moreinformation: "The secure area has access to my resume information, and will grow to include process information, team management information, an emerging markets database, direct documentation download, an array of tools utilised within the process and in depth practicalities of information management.", itemorder: 1}
])
Resumeitem.create!([
  {type: nil, organisation: "Allianz Global Investors", location: "London, UK", title_course: "Director", detail1: "Tasked with introducing and implementing process change", detail2: "Significant turnaround in portfolio performance achieved", detail3: "Development of key stock selection and portfolio construction tools", detail4: " ", detail5: " ", detail6: " ", start_date: "May 2011", end_date: "Present", detail: "Co-Manager of the GEM Equity fund", sections: "Experience", user_id: 2, Moreinformation: nil, extradetail: nil, itemorder: 10},
  {type: nil, organisation: " ", location: " ", title_course: " ", detail1: " ", detail2: " ", detail3: " ", detail4: " ", detail5: " ", detail6: " ", start_date: " ", end_date: " ", detail: "Over 16 years experience in Emerging Market equity.", sections: "Key", user_id: 2, Moreinformation: nil, extradetail: nil, itemorder: 1},
  {type: nil, organisation: "CFA", location: " ", title_course: "Chartered Financial Analyst", detail1: " ", detail2: " ", detail3: " ", detail4: " ", detail5: " ", detail6: " ", start_date: "2001", end_date: "2002", detail: "Attained CFA Charter in October 2002. All exams passed first time.", sections: "Education", user_id: 2, Moreinformation: nil, extradetail: nil, itemorder: 17},
  {type: nil, organisation: "Steer", location: " London", title_course: " Ruby on Rails", detail1: " Able to programme a web app to accept users, accept postings, generate location data and take payments", detail2: " ", detail3: " ", detail4: " ", detail5: " ", detail6: " ", start_date: " June 2014", end_date: " June 2014", detail: "Course teaching the building of web applications using Ruby on Rails", sections: "Education", user_id: 2, Moreinformation: nil, extradetail: nil, itemorder: 21},
  {type: nil, organisation: " ", location: " ", title_course: " ", detail1: " ", detail2: " ", detail3: " ", detail4: " ", detail5: " ", detail6: " ", start_date: " ", end_date: " ", detail: "16 years covering Latin America, 10 years covering EMEA and 8 years covering Asia Pacific ex Japan", sections: "Key", user_id: 2, Moreinformation: "", extradetail: nil, itemorder: 2},
  {type: nil, organisation: " ", location: " ", title_course: " ", detail1: " ", detail2: " ", detail3: " ", detail4: " ", detail5: " ", detail6: " ", start_date: " ", end_date: " ", detail: "Managed single country funds, regional funds, global funds and long short funds – strong track record available on request", sections: "Key", user_id: 2, Moreinformation: "", extradetail: nil, itemorder: 3},
  {type: nil, organisation: " ", location: " ", title_course: " ", detail1: " ", detail2: " ", detail3: " ", detail4: " ", detail5: " ", detail6: " ", start_date: " ", end_date: " ", detail: "Managed a team of 9 in the past", sections: "Key", user_id: 2, Moreinformation: nil, extradetail: nil, itemorder: 4},
  {type: nil, organisation: " ", location: " ", title_course: " ", detail1: " ", detail2: " ", detail3: " ", detail4: " ", detail5: " ", detail6: " ", start_date: " ", end_date: " ", detail: "Managed over £7bn at Aviva Investors", sections: "Key", user_id: 2, Moreinformation: "", extradetail: nil, itemorder: 5},
  {type: nil, organisation: " ", location: " ", title_course: " ", detail1: " ", detail2: " ", detail3: " ", detail4: " ", detail5: " ", detail6: " ", start_date: " ", end_date: " ", detail: "Significant knowledge across stocks, sectors and economies", sections: "Key", user_id: 2, Moreinformation: nil, extradetail: nil, itemorder: 6},
  {type: nil, organisation: " ", location: " ", title_course: " ", detail1: " ", detail2: " ", detail3: " ", detail4: " ", detail5: " ", detail6: " ", start_date: " ", end_date: " ", detail: "Extensive experience of marketing", sections: "Key", user_id: 2, Moreinformation: nil, extradetail: nil, itemorder: 7},
  {type: nil, organisation: " ", location: " ", title_course: " ", detail1: " ", detail2: " ", detail3: " ", detail4: " ", detail5: " ", detail6: " ", start_date: " ", end_date: " ", detail: "Long/Short Experience", sections: "Key", user_id: 2, Moreinformation: nil, extradetail: nil, itemorder: 8},
  {type: nil, organisation: " ", location: " ", title_course: " ", detail1: " ", detail2: " ", detail3: " ", detail4: " ", detail5: " ", detail6: " ", start_date: " ", end_date: " ", detail: "In depth understanding of the asset management industry", sections: "Key", user_id: 2, Moreinformation: nil, extradetail: nil, itemorder: 9},
  {type: nil, organisation: "Aviva Investors", location: "London, UK", title_course: "Head of Emerging Market and Asia Equity", detail1: "Launched one of the first Emerging Market Small Cap funds", detail2: "Developed a new Emerging Market equity process for Aviva", detail3: "Development of Aviva Emerging Markets Absolute return concept", detail4: "Managed a team of 9, with close liaison with Asian based colleagues.", detail5: " ", detail6: " ", start_date: "2008", end_date: "2011", detail: "Built a team from scratch to manage Aviva's £7bn pool of EM and Asian equities (27 funds, 9 benchmarks)", sections: "Experience", user_id: 2, Moreinformation: nil, extradetail: nil, itemorder: 11},
  {type: nil, organisation: "Aviva Investors", location: "London, UK", title_course: "Co head of Emerging Market Equity", detail1: "", detail2: "", detail3: "", detail4: "", detail5: "", detail6: "", start_date: "2006", end_date: "2008", detail: "Responsible for Stock selection across 10 GEM countries", sections: "Experience", user_id: 2, Moreinformation: nil, extradetail: nil, itemorder: 12},
  {type: nil, organisation: "Landsdowne Partners", location: "London, UK", title_course: "Hedge Fund Portfolio Manager", detail1: "Part of the team that set up and marketed the Lansdowne Emerging Market hedge fund", detail2: "", detail3: "", detail4: "", detail5: "", detail6: "", start_date: "2005", end_date: "2006", detail: "Responsible for idea generation on Emerging Market hedge fund and implementation of positions", sections: "Experience", user_id: 2, Moreinformation: nil, extradetail: nil, itemorder: 13},
  {type: nil, organisation: "Wells Capital Management", location: "San Francisco, USA", title_course: "Senior Analyst EMEA Equities", detail1: "Extensive contact with clients and consultants", detail2: "", detail3: "", detail4: "", detail5: "", detail6: "", start_date: "2004", end_date: "2005", detail: "Primary responsibility for EMEA region investment recommendations, stock selection and asset allocation.", sections: "Experience", user_id: 2, Moreinformation: nil, extradetail: nil, itemorder: 14},
  {type: nil, organisation: "F&C Emerging Markets", location: "London, UK", title_course: "Portfolio Manager and Investment Analyst", detail1: "Emerging Market oil & gas specialist providing analysis, input and recommendation for stock selection.", detail2: "Head of Energy Global Sector Team.  Responsibilities include peer review of stock research and inputs for global asset allocation discussions.", detail3: "Strong involvement in a number of committees considering the investment process, particularly asset allocation and Corporate Governance. ", detail4: "Extensive presentational contact with existing and prospective clients.", detail5: "", detail6: "", start_date: "1998", end_date: "2004", detail: "Primary responsibility for South American investment recommendations, member of the team providing investment recommendations for Taiwan.", sections: "Experience", user_id: 2, Moreinformation: nil, extradetail: nil, itemorder: 15},
  {type: nil, organisation: "Coopers & Lybrand", location: "London, UK", title_course: "Auditor", detail1: "Progressed to running an audit team of ten on Royal Sun Alliance Investments audit.", detail2: "Seconded to the Open-ended investment fund department for six months.", detail3: "", detail4: "", detail5: "", detail6: "", start_date: "1995", end_date: "1998", detail: "Audit experience in a wide range of industries finally specialising in financial markets.", sections: "Experience", user_id: 2, Moreinformation: nil, extradetail: nil, itemorder: 16},
  {type: nil, organisation: "ACA", location: "London, UK", title_course: "Chartered Accountancy", detail1: "", detail2: "", detail3: "", detail4: "", detail5: "", detail6: "", start_date: "1995", end_date: "1998", detail: "Passed all three years first time", sections: "Education", user_id: 2, Moreinformation: nil, extradetail: nil, itemorder: 18},
  {type: nil, organisation: "UKSIP", location: "London, UK", title_course: "Investment Management Certificate (IMC)", detail1: "", detail2: "", detail3: "", detail4: "", detail5: "", detail6: "", start_date: "1998", end_date: "1998", detail: "Passed first time", sections: "Education", user_id: 2, Moreinformation: nil, extradetail: nil, itemorder: 19},
  {type: nil, organisation: "Cambridge University", location: "Cambridge, UK", title_course: "MA(hons) Economics", detail1: "", detail2: "", detail3: "", detail4: "", detail5: "", detail6: "", start_date: "1991", end_date: "1994", detail: "Gained a II(i) - key course choice of Underdeveloped Countries in the third year.", sections: "Education", user_id: 2, Moreinformation: nil, extradetail: nil, itemorder: 20},
  {type: nil, organisation: "", location: "", title_course: "", detail1: "", detail2: "", detail3: "", detail4: "", detail5: "", detail6: "", start_date: "", end_date: "", detail: "Avid cyclist, having taking part in the 2013 Etape du Tour", sections: "Other", user_id: 2, Moreinformation: nil, extradetail: nil, itemorder: 22}
])

User.create!([
  {username: "mpwa1", email: "test@mpwa.me", password: "testtest", password_confirmation: "testtest"},
  {username: "mpwa", email: "mark@mpwa.me", password: "testtest", password_confirmation: "testtest"}
])


Viewer.create!([
  {username: "test", email: "test@test", password: "12345678", password_confirmation: "12345678"},
  {username: "test2", email: "test2@test", password: "12345678", password_confirmation: "12345678"}
  ])